[project]
name = "ps-of-py"
version = "0.2.0"
description = "This is a  Python  for Photoshop."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "photoshop-python-api",
    "xlwings",
]
